POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "joe",
  "password": "mypassword"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Secure Blog",
  "author": "Joe",
  "url": "http://secure.com",
  "likes": 5
}